"""LLM provider abstraction"""

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Prompt:
    system: str
    user: str


@dataclass(frozen=True, slots=True)
class LLMResponse:
    sql: str
    raw_text: str
    model: str
    latency_ms: float
    input_tokens: int | None = None
    output_tokens: int | None = None


class BaseLLMProvider(ABC):

    @abstractmethod
    async def generate(self, prompt: Prompt) -> LLMResponse:
        ...

    @abstractmethod
    def name(self) -> str:
        ...

_CODE_BLOCK_RE = re.compile(r"```(?:sql)?\s*\n(.+?)\n```", re.IGNORECASE | re.DOTALL)

# Chain-of-Thought ``<plan>...</plan>`` block — generated by the LLM before
# the SQL when CoT scaffolding is in the user prompt. Stripped first so the
# SELECT/WITH fallback below doesn't pick up keywords mentioned inside the
# plan text (e.g. "plan: ... SELECT name and count").
_PLAN_BLOCK_RE = re.compile(r"<plan\b[^>]*>.*?</plan>", re.IGNORECASE | re.DOTALL)


def extract_sql(raw_text: str) -> str:
    # Strip any <plan>...</plan> block first — the SQL always follows it
    # in the CoT format, so removing it doesn't change ordering.
    text = _PLAN_BLOCK_RE.sub("", raw_text).strip()

    match = _CODE_BLOCK_RE.search(text)
    if match:
        candidate = match.group(1).strip()
        return _strip_trailing_semicolon(candidate)

    if re.match(r"^\s*(SELECT|WITH)\b", text, re.IGNORECASE):
        return _strip_trailing_semicolon(text)

    fallback = re.search(r"(SELECT|WITH)\b.*", text, re.IGNORECASE | re.DOTALL)
    if fallback:
        return _strip_trailing_semicolon(fallback.group(0).strip())

    return _strip_trailing_semicolon(text)


def _strip_trailing_semicolon(sql: str) -> str:
    return sql.rstrip().rstrip(";").rstrip()
